import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          
          <SignedIn>
          <Navbar/>
            {children}</SignedIn>
          <SignedOut>
            <SignIn routing="hash" />
          </SignedOut>
        </body> 
      </html>
    </ClerkProvider>
  );
}
